import { fromEvent } from "rxjs";
import { map, tap } from "rxjs/operators";

const element = document.createElement("div");
element.innerHTML = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse non dui neque. Maecenas ut scelerisque arcu. Sed egestas lobortis eros a laoreet. Nam venenatis ac lacus sed fermentum. Quisque interdum neque sit amet massa tempor condimentum. Maecenas ipsum felis, malesuada quis tristique id, porta sit amet mauris. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/><br/>
Aliquam sit amet egestas nisi. Donec vel velit ac eros varius aliquet. Mauris sagittis auctor risus, placerat rhoncus lorem pulvinar vitae. Nullam placerat, elit in tempus sodales, est nisi porta orci, at vulputate enim arcu non ex. Suspendisse vehicula mi urna, quis vehicula magna volutpat quis. Mauris quis nisi pretium, rutrum dui a, tempor nisl. Nullam luctus vulputate consectetur. Pellentesque imperdiet non tellus congue feugiat. Mauris et sem sit amet ex malesuada ultrices. Nulla nec scelerisque nisi. Cras imperdiet ex vitae commodo ultricies. Phasellus varius, magna vel pellentesque dignissim, eros augue rutrum turpis, ac molestie erat quam sed ipsum. Aenean a ex est. Nulla sapien libero, pulvinar eget magna id, cursus tempus enim. Fusce pharetra nisl sem, id porttitor magna consequat eu.
<br/><br/>
Pellentesque vel metus eget elit feugiat imperdiet. Integer consectetur nisl semper risus tempor, vitae semper metus blandit. Quisque porta ante id sem posuere, in pharetra lectus aliquam. Nulla mollis molestie auctor. Phasellus consequat ornare ultricies. Morbi efficitur sit amet lorem ac mollis. Aliquam eget velit a ex sollicitudin mollis sit amet eu ante. Integer vestibulum, quam quis egestas finibus, augue diam volutpat nibh, tempor tempus erat libero eu turpis. Donec sed nisi fermentum justo gravida pretium et nec est.
<br/><br/>
Sed pharetra mi commodo diam aliquet egestas. Fusce mollis sem in velit pellentesque commodo. Suspendisse potenti. Donec lobortis, mauris eu interdum euismod, est enim vestibulum ipsum, eleifend pharetra ligula libero nec velit. Morbi nec mauris ac arcu tempor bibendum. Ut elit orci, volutpat ac dictum sit amet, molestie aliquet tortor. Nullam id bibendum lectus. Vivamus sodales sit amet felis vitae eleifend. Vestibulum ullamcorper imperdiet velit, gravida placerat dui lacinia a. Mauris id finibus erat, at rhoncus nisi. Pellentesque sed arcu ultricies, maximus erat ac, feugiat turpis. Aenean pharetra lacus odio, id euismod odio commodo non. Cras ac consequat ex, ac commodo tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce sit amet sapien elementum, congue lorem sed, suscipit elit.
<br/><br/>
Integer mi odio, egestas sit amet leo gravida, faucibus mollis enim. Aliquam dapibus at sapien ut tempor. Praesent eu purus a dolor vestibulum malesuada. Sed tempus est vitae pharetra mattis. Nam ornare ultrices mi, vel elementum sapien mattis ut. Integer vel varius nisi, in vulputate odio. Sed interdum libero in enim euismod, quis efficitur tellus dapibus. Ut fermentum metus eget felis ornare rutrum. Aliquam ornare in lorem in blandit. Sed sodales vulputate nunc, a vestibulum risus ullamcorper ut.
<br/><br/>
Mauris accumsan elit sollicitudin ornare ullamcorper. Integer venenatis neque est, id bibendum leo fermentum et. Curabitur vel iaculis lorem. In auctor mollis mi, a tincidunt justo congue at. Nunc mattis est et risus finibus pulvinar. Pellentesque consequat turpis ac fringilla pellentesque. Pellentesque vitae purus ut magna pharetra sagittis. Vivamus et lobortis nibh. Donec eget ultrices nisi. Aliquam efficitur non ante sagittis varius. In hac habitasse platea dictumst. Praesent non odio iaculis arcu rhoncus eleifend. Aliquam nisi sem, vestibulum ut accumsan eget, pellentesque sed nisi.
<br/><br/>
Proin consectetur ac felis a euismod. Ut eu rhoncus ipsum. Phasellus iaculis eu magna a tincidunt. Etiam accumsan justo ut tincidunt interdum. Phasellus odio tortor, tempor vel neque vitae, dapibus mattis massa. Quisque sollicitudin justo non orci egestas blandit. Aliquam erat volutpat. Donec molestie convallis porta. Vestibulum vel ligula vel quam porta gravida. Vestibulum iaculis odio ante, at pretium augue facilisis eu.
<br/><br/>
Suspendisse eleifend tortor nec elit sodales commodo. Vestibulum facilisis condimentum mi, commodo convallis orci ultricies sed. Sed ante libero, lobortis at diam at, aliquet fringilla urna. Cras ullamcorper est et enim posuere, eget semper turpis gravida. Sed pretium auctor mi, vel cursus sem. Maecenas ac purus vel magna sagittis pharetra et et elit. Nunc tincidunt justo gravida porta egestas. Ut pharetra auctor consectetur. Aliquam id maximus sem, id mattis enim. Fusce viverra finibus enim quis eleifend. Sed sed tellus nec nulla consequat viverra non eget nulla. Vivamus sit amet ligula velit.
<br/><br/>
Morbi ac magna commodo purus hendrerit volutpat quis et mi. Sed sed rutrum metus, sed bibendum orci. Pellentesque sit amet nulla sit amet lacus laoreet laoreet vitae eget risus. Pellentesque tempor ante sapien, at viverra dui scelerisque in. Vestibulum ex ipsum, varius vitae porttitor ac, iaculis vel diam. Nullam dictum eros purus, nec blandit lorem tristique in. Suspendisse non laoreet velit. Duis ornare massa urna, ac venenatis lorem condimentum nec. Pellentesque fringilla diam est, sed rutrum erat congue vel. Praesent lobortis, ipsum vel ullamcorper ullamcorper, mauris mauris tristique orci, vel porta nulla turpis non quam. Suspendisse ut massa eu purus pretium dapibus. Aenean at venenatis odio. Nam venenatis laoreet purus quis luctus.
<br/><br/>
Aenean a justo tempus, sagittis libero quis, ultrices nisi. Nullam accumsan metus eget lectus mattis egestas. Etiam ac enim a nibh elementum euismod et varius ex. Integer luctus dapibus dui in fermentum. Aliquam quis ante a ante ullamcorper varius a sit amet libero. Aliquam euismod consequat eros, quis aliquet massa vulputate vel. Curabitur et leo felis. Nam tempus sed turpis ac lacinia. Praesent sem felis, fermentum sed lacinia ac, elementum sed eros. Donec vitae velit in libero dictum consectetur.
<br/><br/>
Praesent bibendum efficitur scelerisque. Nam suscipit et libero sed bibendum. Nulla tristique suscipit ipsum, et sagittis ligula tempor id. Curabitur in ornare dolor. Mauris volutpat lobortis egestas. Vestibulum massa nisi, convallis non lorem facilisis, malesuada efficitur ligula. Suspendisse volutpat felis sed felis varius, sit amet dapibus nisi tempor. Duis consequat ullamcorper purus, ac volutpat libero vehicula ut. Donec sollicitudin tortor vel augue tincidunt, sit amet lacinia sem consequat. Vivamus aliquam metus orci, in malesuada lacus ullamcorper quis. Aenean rhoncus rutrum nunc, a placerat ipsum aliquet id. Cras pellentesque suscipit rutrum. Donec vitae velit nec nibh fermentum aliquet. Proin nec convallis ante. Nulla finibus ante et commodo pellentesque. Cras vitae risus dictum, consequat massa eget, vulputate nisl.
<br/><br/>
Sed eget consequat odio, id tincidunt enim. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc sed urna tempor, tincidunt risus a, ultrices urna. Nunc consectetur, dolor sit amet feugiat facilisis, est lectus euismod mauris, a condimentum odio lectus a enim. Suspendisse venenatis vel dui sed commodo. Quisque semper elementum viverra. Vestibulum vel sodales leo. Nullam dui libero, venenatis non interdum vel, pretium sit amet est. Proin maximus odio velit, id vulputate metus congue ut. Nam eu lacus lobortis, lobortis tortor non, pharetra urna. Morbi in interdum libero. Duis tincidunt iaculis consectetur. Proin posuere justo at erat lacinia, sit amet cursus arcu imperdiet. Donec luctus ipsum sed nulla posuere, nec egestas odio vehicula. Sed consequat sapien eget hendrerit condimentum. Vestibulum tincidunt rutrum lorem, in vulputate odio finibus sed.
<br/><br/>
Morbi aliquet, felis non mattis consequat, diam dui eleifend est, sit amet feugiat arcu arcu eu tellus. Cras at porttitor dui, ac commodo leo. In hac habitasse platea dictumst. Sed iaculis felis eu massa dictum, vel dictum sem porta. Vestibulum porta quam sit amet quam aliquet dictum. Praesent sed sollicitudin dui. Nullam non risus at dolor suscipit laoreet ut in diam. Nunc luctus odio et lorem pharetra interdum. Proin placerat est at tortor suscipit, sit amet pellentesque ex molestie. Aliquam accumsan porttitor euismod. Cras semper urna bibendum velit vulputate ornare. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam fermentum rhoncus auctor. Aenean placerat erat dignissim leo porta rutrum. Interdum et malesuada fames ac ante ipsum primis in faucibus.
<br/><br/>
Duis sodales lectus laoreet risus tincidunt, et sodales dui faucibus. Cras at augue sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur tristique quam ut metus pellentesque porttitor. Praesent bibendum nisi dolor, pharetra elementum felis facilisis vel. Proin dui purus, sagittis id mollis ac, tincidunt vel ante. Nulla eu pellentesque nibh. Duis posuere quam tempor laoreet commodo. Sed a egestas nisi, sed accumsan leo.
<br/><br/>
Vivamus libero nunc, facilisis vitae quam vitae, maximus dapibus velit. Donec nibh massa, porttitor at erat a, luctus porttitor mauris. Aenean faucibus dolor sagittis fermentum tempor. Nunc quis mi imperdiet, vestibulum massa vel, accumsan justo. Sed laoreet dolor non ex laoreet porta. Vestibulum sodales nulla ante, quis ornare nunc volutpat in. Nam maximus pretium magna, at porta eros malesuada quis.
<br/><br/>
Aliquam elementum elementum dui, vulputate feugiat arcu rhoncus quis. Proin in metus bibendum urna posuere consequat in at lectus. Quisque gravida pulvinar ipsum pharetra hendrerit. In iaculis blandit orci, quis condimentum est blandit ut. Donec scelerisque pretium egestas. Vivamus pellentesque elit at nunc placerat, vitae euismod nibh rutrum. Pellentesque et enim pellentesque, sollicitudin elit eget, sodales libero. Pellentesque lacinia eros et lorem rutrum finibus. Nullam congue suscipit nulla, eget ornare nisi ornare ut. Vestibulum laoreet magna in massa sagittis, sit amet tincidunt purus sodales. Ut lobortis viverra lorem et pellentesque. Integer pulvinar turpis nec velit laoreet tempus finibus sit amet massa. Sed convallis metus quis lectus auctor, et tempus augue lacinia. Duis sed nunc vel justo tincidunt maximus non in nibh. Cras lacus felis, sollicitudin sit amet odio eu, semper tincidunt leo. Vivamus pellentesque aliquam est nec ultricies.
<br/><br/>
Pellentesque lectus purus, fringilla vitae augue a, sollicitudin condimentum metus. Sed eu metus massa. Suspendisse potenti. Mauris euismod, quam in luctus ultricies, ligula nisl mollis magna, et tempor magna mi condimentum neque. Duis lobortis euismod congue. Nunc in risus vulputate, ultrices nisi ut, malesuada metus. Sed ac purus sollicitudin, ullamcorper magna vehicula, luctus eros. Sed eu massa laoreet, suscipit quam at, mattis felis. Aenean enim orci, semper quis posuere vel, dictum nec mauris. Fusce at blandit libero, ac facilisis justo. Proin sodales, quam vitae bibendum efficitur, ex massa egestas eros, ac lobortis mi eros ac odio. Suspendisse sit amet pellentesque nisl, eget blandit quam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
<br/><br/>
Suspendisse sed massa suscipit, facilisis tortor ac, tincidunt nisl. In tristique, justo id sodales fringilla, lacus turpis consectetur ligula, non viverra justo mi quis orci. Nulla venenatis tempor purus eget eleifend. Nullam sapien lorem, congue et egestas eu, luctus ac est. Integer dignissim, sem id laoreet accumsan, est metus dignissim lorem, vel posuere orci tortor non libero. Proin molestie sapien eu urna molestie viverra. Proin fringilla eros ac felis sodales, vel condimentum justo mollis. Proin at sem in dolor tristique aliquet id molestie nibh. Nullam ultrices augue pulvinar diam consequat, vel condimentum arcu vestibulum. Proin commodo ligula vel neque rhoncus, vitae rhoncus nulla porttitor. Nulla a mauris ultrices urna volutpat tincidunt. Nullam elementum lectus cursus mauris dictum, quis dignissim velit tempus. Mauris dapibus justo ut auctor cursus.
<br/><br/>
Donec placerat sem felis. Cras nunc nunc, pulvinar ut diam a, efficitur elementum enim. Phasellus hendrerit consequat ornare. Nullam feugiat eleifend odio, vel mattis eros dapibus id. Sed finibus odio in augue molestie congue. Nunc fermentum, purus et varius commodo, ante sem luctus felis, dapibus condimentum turpis elit nec leo. Ut sed porttitor lacus. Ut aliquam augue sem, nec porttitor nunc sagittis vitae. Suspendisse eu leo ac nisi porttitor condimentum. Quisque blandit nibh sit amet nisl mattis ullamcorper. Nam gravida sem ut mauris suscipit, ut tempus turpis facilisis. Nam tempus rhoncus urna eget efficitur.
<br/><br/>
Suspendisse porta nunc turpis, eu faucibus lacus volutpat et. Vivamus imperdiet tellus et nisl mattis, nec lobortis purus imperdiet. Pellentesque malesuada malesuada leo quis tincidunt. Sed cursus auctor dictum. Phasellus et ante non ex vestibulum cursus. Nulla velit lacus, malesuada sed posuere nec, porttitor a massa. Phasellus placerat augue id diam condimentum, in rhoncus diam tristique. Vestibulum justo enim, dictum at congue non, feugiat nec ante.
<br/><br/>
Aenean rutrum lacinia ante, sit amet congue elit bibendum euismod. Maecenas consequat nulla erat. Cras luctus blandit odio, ut feugiat elit imperdiet vel. Sed laoreet mauris at lorem suscipit maximus. Sed vitae massa dui. Vestibulum vehicula pharetra vulputate. Nulla vitae viverra odio. Nunc fringilla accumsan blandit. Quisque convallis velit quis varius iaculis. Nunc posuere mi semper quam fermentum tincidunt. Curabitur ullamcorper dolor vel mauris varius finibus. In accumsan tellus porta justo auctor, ut pulvinar ipsum facilisis. In non ex eu ante pellentesque ornare in mattis erat. Ut ullamcorper metus non nisi dignissim, ac malesuada sem condimentum.
<br/><br/>
Pellentesque iaculis neque odio, sed volutpat tellus efficitur tincidunt. Proin varius justo sed finibus ornare. Nulla id posuere nulla, vel semper magna. Aliquam sagittis lectus a sem suscipit, nec venenatis dui mattis. Ut aliquet orci mi, a volutpat nisi lacinia quis. Curabitur maximus sem a orci semper, in rutrum massa molestie. Suspendisse potenti. Nam consectetur cursus elit vitae varius. Nulla at felis nec lacus porta aliquet. Ut pharetra ante in arcu mattis, ut eleifend mi elementum. Cras egestas efficitur sem, ut placerat quam tristique vel. Phasellus ac convallis erat. Nulla volutpat neque quis nisi feugiat, in aliquet lacus condimentum. Curabitur malesuada, lacus nec malesuada varius, ipsum est ornare nisi, eget gravida ligula felis eu dui. Proin tempus ligula ligula, ut viverra felis ornare id. Mauris aliquam erat a turpis faucibus, vitae interdum orci accumsan.
<br/><br/>
Vestibulum in iaculis orci. Cras eleifend fermentum arcu, in feugiat purus efficitur vitae. Cras vel semper turpis. Nunc vel bibendum risus. Pellentesque non dui a dui tempus placerat. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis blandit sapien mi, sit amet mollis dolor aliquet in. Nunc porta nunc metus, eget elementum nulla varius egestas. Nulla condimentum leo in dui facilisis placerat. Duis convallis diam sed nisi convallis volutpat. Donec rhoncus vulputate quam a pulvinar. Donec fringilla justo non eros consectetur, quis mattis lorem sagittis.
<br/><br/>
Nunc rhoncus dolor dolor, mollis auctor nisi vestibulum ut. In efficitur pulvinar tincidunt. Nunc pretium ut nisi vel bibendum. Maecenas eget dapibus elit. Sed vestibulum augue id ligula euismod dapibus. Aenean in fermentum ipsum. Etiam eu velit sit amet mi ullamcorper rutrum. Sed ut vehicula turpis. Sed volutpat tincidunt mollis. Maecenas quis leo id lacus venenatis tempor non in orci. Maecenas lobortis ultrices viverra. Aliquam quis congue mi, a maximus erat.
<br/><br/>
Quisque ornare ante eget arcu rutrum pharetra. Aliquam varius congue nulla, dictum dignissim risus sodales tincidunt. Phasellus lacinia malesuada cursus. Praesent interdum aliquam cursus. Duis tincidunt risus in dolor commodo aliquam at a elit. Nulla vehicula felis at felis maximus malesuada. Quisque pharetra, erat fermentum ultrices semper, turpis diam consectetur dui, ut dignissim erat erat lacinia risus. Morbi facilisis velit at justo condimentum venenatis. Mauris venenatis leo sed est tempor egestas. Aliquam erat volutpat. In hac habitasse platea dictumst. Quisque condimentum finibus congue. Proin quam mauris, lacinia ac dapibus id, pulvinar a lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus.
<br/><br/>
Cras at dolor quis sapien fringilla porta. Proin volutpat, lectus id congue pellentesque, diam lacus laoreet urna, sed tincidunt neque nulla et felis. Donec commodo neque malesuada turpis elementum ornare. Nunc efficitur non leo non ornare. Proin sed neque sodales, sodales velit id, varius nibh. Mauris enim risus, venenatis ut libero in, condimentum pulvinar lectus. Aenean nec metus iaculis, euismod nisl ac, posuere nibh. Sed arcu ante, faucibus quis libero eget, blandit convallis orci. Praesent ut dictum lorem, a ultricies erat. Nulla fringilla velit id dolor iaculis tempus. Sed imperdiet, turpis vel euismod sollicitudin, orci mi fermentum felis, in aliquam purus libero ut ex.
<br/><br/>
Mauris a nibh dui. Mauris ipsum risus, dictum quis libero in, aliquam faucibus nisl. Quisque auctor, nisl ut tincidunt laoreet, ante lectus dapibus mauris, ut scelerisque purus ante non ante. Sed volutpat mi eu massa efficitur, in blandit lectus fermentum. Quisque at ultricies mi, et gravida dolor. Donec id molestie nibh. Etiam in cursus ex, id hendrerit ex. Vivamus finibus, libero a fringilla viverra, purus erat porttitor ipsum, ut pharetra enim orci eget elit. In non nisl arcu. Curabitur varius ligula libero, ac feugiat sapien sollicitudin eget. Nullam ac diam quam. Quisque ullamcorper suscipit tristique. Cras ante lorem, pulvinar id faucibus sed, tincidunt ac orci. Aenean auctor felis nec hendrerit finibus. Cras est neque, sollicitudin nec hendrerit eu, vestibulum sed sapien.
<br/><br/>
Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed id justo nec massa scelerisque semper ut bibendum dolor. Praesent in sodales tellus. Pellentesque eu ex viverra, egestas ligula nec, auctor dolor. In hac habitasse platea dictumst. Integer egestas vestibulum dolor, id sodales lectus malesuada sed. Ut ut commodo lacus.
<br/><br/>
Aenean quis posuere nibh. Aliquam enim massa, scelerisque a massa in, volutpat semper velit. Nunc sodales diam non justo accumsan dapibus. Morbi suscipit pharetra lectus ut maximus. Nulla tempus nulla sit amet nisi sollicitudin eleifend. Phasellus augue massa, consequat quis dignissim vitae, mattis eu erat. Duis eleifend, mauris sit amet porta sodales, mi tortor pretium diam, ac tempor ante felis in enim.
<br/><br/>
Pellentesque vitae dui rutrum, facilisis turpis vitae, sollicitudin justo. Cras a accumsan nulla. Donec vel convallis quam. Maecenas mollis sit amet diam non eleifend. Ut ullamcorper neque luctus sem pharetra, in tincidunt metus fringilla. Curabitur eleifend urna et enim sollicitudin, nec maximus lectus ultrices. Quisque sed accumsan sapien, non blandit justo. Nunc semper cursus mi, in interdum magna sollicitudin vitae.
<br/><br/>
Etiam congue ante fringilla est venenatis tincidunt. Proin metus est, venenatis ut consequat eu, efficitur et lacus. Fusce faucibus sodales aliquet. Aenean ultrices diam ac tortor molestie hendrerit. Aenean a cursus sem. Vivamus ac ex eu nunc sodales pretium ac eget leo. Curabitur et interdum felis. Maecenas semper eleifend libero, quis feugiat odio ullamcorper ac. Praesent non augue odio. In dapibus gravida leo, eu viverra massa scelerisque sed. Suspendisse vel lorem enim.
<br/><br/>
Phasellus dictum eleifend mi, sit amet tincidunt eros gravida vitae. Mauris nec odio ex. Proin accumsan et nisi vitae ultrices. Vestibulum eget congue sem, nec varius lectus. Aenean eu nisl nec lorem luctus commodo quis in nibh. Maecenas ac scelerisque elit, id sagittis nisi. Phasellus cursus dolor vitae augue malesuada ornare. Morbi vel aliquam dui, ut condimentum nisi.
<br/><br/>
Nunc laoreet nunc non placerat dapibus. Duis erat enim, tincidunt sed quam sed, porttitor suscipit est. Sed fermentum tempus velit, ut consectetur enim sollicitudin rhoncus. Ut ac urna consectetur, cursus tortor quis, gravida augue. Nunc neque sapien, commodo sit amet cursus ut, consectetur quis nunc. Duis cursus mauris non libero tempus fringilla. Quisque at nulla eu ligula vestibulum egestas a quis mauris. Nullam quis tristique quam. Sed ac egestas quam, sit amet porta dolor. Sed eu lacus euismod, pretium urna nec, eleifend nulla. Integer iaculis ullamcorper erat vel interdum. Aenean eleifend odio sit amet sapien maximus, in tincidunt neque vestibulum. Nunc quis dapibus tortor. Aenean justo est, eleifend lobortis magna quis, vehicula pharetra est.
<br/><br/>
Mauris purus est, ultrices vel justo vitae, egestas luctus tellus. Morbi justo libero, fermentum dapibus eros non, porta facilisis diam. Donec luctus enim odio, ac pretium nisl pharetra vel. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus efficitur arcu nibh, a faucibus mi tempus eu. Quisque nunc neque, volutpat non odio at, tempus accumsan ante. Quisque tempus viverra maximus. Morbi at diam posuere, consectetur arcu id, tempus nisi. Phasellus placerat sem vel risus accumsan, ut laoreet turpis cursus. Integer condimentum tempor accumsan.
<br/><br/>
Sed at tellus eget ligula convallis tincidunt. Nullam laoreet ultricies odio, et dignissim risus elementum a. Sed non odio pellentesque, cursus turpis et, eleifend ligula. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin a tincidunt massa. Nulla purus turpis, lobortis maximus mollis eget, vehicula et odio. Nulla aliquet gravida quam, in sollicitudin arcu venenatis quis.
<br/><br/>
Morbi vel lobortis ante. Quisque vitae nisl mattis, ullamcorper diam quis, eleifend lorem. Ut nec bibendum eros, ac varius velit. Vestibulum vel elementum lorem. Curabitur quis magna non lorem placerat semper at eu neque. In blandit, odio sed dapibus ullamcorper, tellus dui cursus neque, quis volutpat est massa vitae elit. Curabitur semper, augue quis ultrices tincidunt, urna sapien vestibulum lacus, id condimentum risus felis ac nisl. Curabitur erat nulla, consectetur nec semper eget, imperdiet in risus. Fusce tempor nunc nec aliquet convallis. Duis suscipit nec risus sit amet convallis. Duis vehicula mollis sollicitudin.
<br/><br/>
Maecenas elementum fringilla convallis. Maecenas ac enim quis nisl feugiat tristique eget ac felis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi vitae velit vitae nisi consectetur laoreet non et odio. Pellentesque non blandit urna. Vivamus dictum nisl et libero euismod vulputate. Aliquam quam quam, malesuada et lacinia non, accumsan eu tellus. Etiam accumsan tincidunt congue. Nam placerat feugiat metus, cursus consectetur est lobortis a. Duis velit diam, aliquam id tellus id, pharetra consequat dui. Curabitur sed eros lorem. Sed finibus quam vitae euismod ullamcorper.
<br/><br/>
Nunc quis odio sed odio feugiat aliquet. Proin non erat quis tellus lobortis dignissim. Donec elementum ex mauris, sed luctus turpis scelerisque ut. Donec eget urna laoreet, aliquet diam in, cursus lorem. Nulla ac varius lectus. Integer bibendum congue convallis. Quisque ut viverra est. Suspendisse scelerisque eget lectus faucibus porta. Etiam pretium leo risus, sed maximus leo vehicula nec. Pellentesque at efficitur enim, sit amet iaculis massa.
<br/><br/>
Nam magna dolor, euismod eu egestas vel, vestibulum vel nisl. Vestibulum sollicitudin, sem at posuere egestas, nisi dui egestas arcu, nec pellentesque lectus diam sit amet ligula. Pellentesque suscipit odio a neque interdum, non tempus nisl ultricies. Proin odio lectus, convallis at mi eu, elementum fermentum nisl. Ut eget eleifend lorem. Suspendisse in fermentum sem. Quisque tempor lacus id venenatis fringilla. Phasellus eros risus, porta et est nec, euismod vulputate tortor. Nam volutpat, risus at consequat tincidunt, diam massa viverra odio, at convallis sem felis sed nunc. Etiam non porttitor augue. Nulla eget egestas tellus.
<br/><br/>
Sed ut egestas tortor, a euismod tortor. Donec ut nisi vitae tellus placerat finibus. Pellentesque vitae finibus elit, ut suscipit elit. Integer varius quam a sem tempor rutrum nec nec justo. Pellentesque et lorem vitae diam interdum placerat sed aliquam libero. Nulla facilisi. Morbi sapien eros, suscipit eu mollis a, posuere vel nibh.
<br/><br/>
Aliquam nisi lorem, elementum vel auctor ut, eleifend ut massa. Sed est purus, luctus at pharetra non, gravida lacinia velit. Phasellus hendrerit mattis nisl at placerat. Curabitur eget scelerisque turpis, eget fermentum arcu. Nunc iaculis, ex nec finibus ornare, nisl tellus placerat urna, sed tincidunt eros felis nec erat. Aliquam et augue maximus, porta turpis id, lobortis libero. Etiam porta arcu non elementum laoreet.
<br/><br/>
Pellentesque tristique dignissim sagittis. Nulla nec dapibus dolor. Mauris porttitor urna at nibh porttitor eleifend. Vivamus rhoncus imperdiet purus in interdum. Donec eleifend, leo in aliquam varius, tellus nulla cursus purus, a bibendum velit justo nec ligula. Ut rhoncus placerat tortor. Duis congue sem vitae arcu blandit lacinia. Nunc et dui augue. Nulla dui arcu, dictum non magna eget, vulputate gravida ipsum. Nam eu velit metus.
<br/><br/>
Vivamus faucibus non arcu a faucibus. Etiam venenatis, velit non efficitur scelerisque, erat ex vehicula libero, eu cursus quam libero vel nisl. Sed in massa lorem. Nullam at dolor ultricies, pulvinar dui ac, finibus mi. Aenean ultrices dolor quis egestas aliquet. Etiam congue dolor venenatis nunc scelerisque placerat. Ut ultricies nisl nibh, at venenatis ipsum hendrerit vitae. Curabitur neque sapien, laoreet eget faucibus quis, tincidunt eu sapien.
<br/><br/>
Etiam magna erat, lacinia eu nibh eu, euismod fringilla urna. Aliquam in orci tempor, hendrerit odio vitae, rhoncus quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur ac hendrerit lectus. Cras at urna vel est suscipit dapibus sed egestas mauris. Aenean et aliquet massa. Fusce ornare id sapien at placerat. Nunc non justo vel dui vulputate consectetur eget sed est. Ut congue ornare tellus, ut mattis est rutrum gravida. Sed tristique ornare dui, vitae pharetra sapien sollicitudin auctor. Morbi a lectus non sem aliquet vehicula. Proin consectetur mi eget quam semper, ut ultrices diam eleifend. Vivamus et dolor varius, luctus libero nec, interdum nibh.
<br/><br/>
Donec ante lacus, auctor et purus id, blandit aliquam arcu. In quis ullamcorper magna, in luctus lectus. Vestibulum in purus massa. Nunc libero urna, egestas nec pretium ac, feugiat id lectus. Aliquam erat volutpat. In tincidunt turpis eget tempus dictum. Ut tristique euismod luctus. Maecenas sollicitudin lorem in justo tincidunt, sed viverra tortor laoreet. Quisque tempor metus sed elementum porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis viverra sapien et enim suscipit tempor. Aliquam erat volutpat.
<br/><br/>
Nulla ultrices, ante et maximus commodo, ipsum tellus aliquam nunc, sit amet lobortis risus arcu eget lacus. Curabitur id sapien eget nunc vulputate auctor a eget sapien. Quisque tincidunt, orci ac iaculis suscipit, arcu eros dictum tortor, eget fringilla nibh leo ut est. Integer pretium massa ac massa tincidunt maximus in venenatis nisl. Sed congue eleifend molestie. Sed suscipit rhoncus urna, ut hendrerit sem tempus vitae. Nam sagittis lectus massa, ac facilisis neque viverra ac. Cras scelerisque maximus magna, ut rutrum nibh convallis vitae. Sed convallis blandit volutpat. Sed vestibulum dignissim magna, eu accumsan tellus. Proin velit sapien, pharetra vitae diam vitae, commodo finibus purus. Nunc accumsan sit amet enim eget tristique. Fusce luctus scelerisque sapien.
<br/><br/>
Nam libero sem, eleifend ac lobortis et, viverra a felis. Praesent suscipit ligula sed nulla sagittis luctus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent eu tellus a neque facilisis accumsan ac non enim. Nulla facilisi. Aenean nisi nisl, vulputate eu diam in, rutrum tempus nisi. Phasellus hendrerit lacus sit amet varius vehicula. Mauris sed consequat dui. Donec eget imperdiet ipsum. Vivamus et est non sapien rutrum vulputate. Aenean laoreet felis id eros consequat, in tincidunt ipsum aliquet. Nulla pretium lobortis risus. Sed tempus massa tortor, non consequat augue vulputate ut. Praesent enim risus, fringilla nec dolor nec, accumsan aliquet eros. Duis in leo vulputate, volutpat ligula a, scelerisque massa.
<br/><br/>
Proin ornare gravida ligula, non fermentum elit vestibulum et. Vestibulum a dolor vel diam vulputate tristique. Quisque nunc dolor, ultricies non ligula vel, condimentum placerat metus. Nam gravida, lorem ullamcorper interdum molestie, tellus lacus ultricies massa, non lacinia eros lorem sed magna. Phasellus tellus eros, efficitur at luctus ut, efficitur a lacus. Nullam auctor tincidunt nisl quis feugiat. Pellentesque gravida at lectus a porta. Nulla scelerisque ligula in turpis ultricies interdum. Phasellus facilisis sit amet nunc vel sollicitudin. Integer varius bibendum elit ac mattis. Donec vel enim ut enim aliquam volutpat vitae eget massa. Pellentesque laoreet molestie tellus, eget maximus ante interdum non. Suspendisse potenti. Fusce dictum iaculis elit quis sodales. Nunc consectetur malesuada odio, sit amet sodales velit feugiat eu.
<br/><br/>
Nunc pellentesque libero quis enim sollicitudin, vitae interdum nunc varius. Nulla elit sem, commodo vitae laoreet et, hendrerit eget elit. Nullam feugiat eros lorem, vitae consequat turpis lacinia sed. Cras vulputate urna vel ante blandit pellentesque. Pellentesque ipsum tortor, vulputate at pharetra nec, ornare pellentesque ex. Pellentesque pretium, erat id pretium pharetra, nunc sapien pellentesque ex, vel volutpat quam augue sit amet leo. Nullam tincidunt efficitur laoreet.
<br/><br/>
Integer convallis fermentum lorem at tempor. Ut vitae lobortis velit. Pellentesque pulvinar nibh purus, quis eleifend purus tempus egestas. Suspendisse varius scelerisque posuere. Nulla consequat justo sit amet ligula tristique varius. Phasellus faucibus nisl nec purus tristique varius. In pharetra diam ut faucibus luctus.
<br/><br/>
Curabitur hendrerit dictum augue et faucibus. Aliquam tempor, nisl in egestas iaculis, enim magna porttitor nulla, ac sodales dui ante ullamcorper magna. Aliquam erat volutpat. Sed ipsum enim, varius in hendrerit in, mattis ut erat. Curabitur vestibulum hendrerit semper. Maecenas vestibulum porttitor lectus, sit amet interdum justo mattis et. Phasellus pharetra mi lacus, quis tristique nisl pulvinar nec.
<br/><br/>
Praesent at nisl a sem tincidunt euismod. Pellentesque ante tellus, malesuada et felis vel, vulputate fringilla libero. Aenean vestibulum faucibus molestie. Curabitur dui elit, feugiat fringilla elementum vitae, consectetur non eros. Etiam non nibh aliquam, condimentum arcu tincidunt, eleifend est. Nam sed finibus augue, sed sodales ante. Fusce turpis eros, egestas vel elit nec, feugiat tincidunt urna. Duis vitae quam vitae lacus convallis vulputate ac et ligula. Proin nunc lectus, lobortis vitae eleifend in, iaculis sit amet lacus. Integer vehicula venenatis lorem, sed sodales nisi molestie ac. Donec id massa sagittis, luctus eros sed, lacinia ipsum. Aliquam id fermentum purus, sit amet eleifend lectus.
<br/><br/>
Morbi vitae tortor rutrum ligula lobortis suscipit. Nulla in nunc tortor. Etiam rutrum eros nec vestibulum pulvinar. Duis id velit pretium, convallis ex imperdiet, congue nisi. Quisque vulputate mollis mauris id varius. Nullam lobortis leo dolor, id laoreet ligula pellentesque eu. Maecenas dictum, mauris non vulputate lobortis, nunc justo molestie ligula, id gravida lorem nunc lobortis tellus. Phasellus dictum aliquam ullamcorper. Suspendisse fermentum turpis ac magna ultrices, a fringilla purus ultrices. Pellentesque nunc sem, convallis ut orci maximus, accumsan pellentesque nunc. Proin scelerisque tempor nisl et porttitor. Cras molestie nisi interdum tincidunt tristique. Sed tempus tincidunt risus in semper. Ut aliquet ligula nec eros varius, eget scelerisque sem pellentesque.
<br/><br/>
Donec eu tellus quam. Mauris volutpat, est in convallis malesuada, orci turpis feugiat urna, fringilla facilisis mauris quam at quam. Etiam interdum leo purus, euismod pharetra mi congue ut. Aenean mollis, diam finibus sollicitudin ultrices, sapien nunc finibus nunc, a mattis enim sem ut leo. Aenean pellentesque eros ultricies metus porta, et ullamcorper risus bibendum. Suspendisse dictum rhoncus mauris, at tincidunt tortor posuere sed. Nunc in ornare lectus. Pellentesque vel augue libero. Fusce sollicitudin sapien ut elit porta sagittis. Nulla ex ligula, placerat sit amet urna non, tempus gravida est. Vestibulum ac pharetra ex, quis commodo nisl. Phasellus efficitur, ante nec semper interdum, libero est vehicula ex, pharetra faucibus turpis dui sed metus. Phasellus sit amet magna et eros euismod malesuada quis vitae ex. Donec in eros ac urna fringilla ornare. Morbi ornare eu orci in dictum.
<br/><br/>
Sed iaculis sapien sapien, sit amet posuere orci faucibus eget. Vestibulum orci lacus, pharetra id interdum a, hendrerit ut leo. Fusce ullamcorper arcu id placerat tempor. Sed vel massa vitae urna rhoncus ullamcorper. Donec pulvinar vitae ex in placerat. Aliquam quis sem porta, condimentum magna sit amet, iaculis eros. Integer vulputate, nibh quis efficitur hendrerit, sem justo pretium erat, eget vehicula odio nisi vel lorem. Nam condimentum suscipit blandit. Suspendisse nec maximus ex, porttitor fermentum urna. Quisque ut nibh tincidunt, aliquam ipsum eget, venenatis massa. Mauris condimentum leo sit amet nibh cursus auctor. Vestibulum a pretium sem. Curabitur eget feugiat arcu. Donec bibendum suscipit tempor. Fusce auctor facilisis vulputate. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
<br/><br/>
In fringilla ligula sed mi cursus sodales. Aliquam enim tellus, posuere cursus nisi vitae, pretium tincidunt massa. Donec odio ante, viverra vitae urna eget, eleifend bibendum elit. Nullam volutpat eros eget leo tristique volutpat. Mauris vitae dolor iaculis, vestibulum diam at, iaculis magna. Vestibulum vestibulum nisi at sagittis pulvinar. Nunc nec tortor quis libero volutpat viverra.
<br/><br/>
Nunc placerat in lacus ut gravida. Integer bibendum, nulla vitae tempor luctus, velit tellus imperdiet purus, at tincidunt massa ex ut magna. Donec pharetra diam mi, a malesuada odio viverra et. Aenean eget nisl quis dui dignissim iaculis et eu risus. Sed tincidunt finibus urna in varius. Sed auctor quam sed tellus volutpat, id accumsan ante commodo. Morbi mattis tortor ac augue euismod sodales. Nullam ac feugiat turpis.
<br/><br/>
Ut orci nibh, tincidunt pretium imperdiet et, lacinia et nulla. Etiam dapibus, ex vel finibus commodo, felis risus dapibus sem, at pretium leo massa ac tortor. Nam vel rhoncus nisl. Nunc luctus mi in mauris rhoncus, ut rutrum nisl accumsan. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin consectetur laoreet nibh et imperdiet. Nam ipsum nisl, aliquet in laoreet et, molestie non diam. Vivamus aliquam, metus a facilisis iaculis, nunc neque feugiat magna, quis vestibulum felis metus eu mi. Vivamus id lacus feugiat, accumsan diam vitae, rutrum nibh. Etiam eleifend nunc eget urna sagittis, id semper turpis tincidunt. Vivamus eget eleifend lorem. Aliquam suscipit lorem non ligula volutpat, ut vestibulum metus auctor. Donec molestie dolor vitae nunc dignissim, et rhoncus erat bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam diam massa, ultrices in nunc eget, lacinia tincidunt lacus. Praesent convallis ante quam.
<br/><br/>
Nulla rhoncus sapien et metus viverra maximus. Duis id ex molestie, lobortis est sit amet, suscipit magna. Mauris sodales, ipsum et maximus hendrerit, nulla sapien dapibus diam, eu suscipit libero nibh ultricies odio. Aenean finibus libero eu diam pellentesque, sit amet accumsan sapien posuere. Fusce fermentum facilisis felis. Nunc imperdiet elit vel metus malesuada tincidunt. Integer placerat felis eget eleifend iaculis. Fusce tellus urna, tristique blandit scelerisque a, placerat a diam. Aliquam pretium erat eget congue lobortis. Integer bibendum vitae quam sed laoreet. Integer at tristique felis. Aliquam erat volutpat. Nam metus elit, placerat id justo at, gravida pretium ligula. Vivamus pulvinar, lectus viverra mollis dictum, lacus eros molestie dolor, sed elementum mi ex in metus.
<br/><br/>
Nullam vitae lacus quis enim feugiat convallis nec non nibh. Aliquam luctus urna a gravida maximus. Nam gravida venenatis ex, eu placerat leo imperdiet vitae. Donec ac massa nec nisi iaculis fringilla vel id mauris. Donec finibus, lorem quis pretium sollicitudin, orci felis euismod lectus, eu convallis leo elit viverra quam. Etiam vel tempus metus. Morbi eu ligula nisl.

`;

const body = document.querySelector("body");
body.append(element);

const progessBar = document.createElement("div");
progessBar.setAttribute("class", "progress-bar");
body.append(progessBar);

// Transform scroll to width
const calculatePercent = (event) => {
  const { scrollTop, scrollHeight, clientHeight } =
    event.target.documentElement;

  return (scrollTop / (scrollHeight - clientHeight)) * 100;
};
// Streams
const scroll$ = fromEvent(document, "scroll");
const width$ = scroll$.pipe(map(calculatePercent), tap(console.log));

width$.subscribe((prc) => {
  progessBar.style.width = `${prc}%`;
});
